apiVersion: v1
kind: Service
metadata:
  name: kafka-k3s
  labels:
    app: kafka-k3s
spec:
  type: NodePort
  ports:
    - port: 9092
      nodePort: 30092
      name: client
  selector:
    app: kafka-k3s
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kafka-k3s-pdb
spec:
  selector:
    matchLabels:
      app: kafka-k3s
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-k3s
spec:
  selector:
    matchLabels:
      app: kafka-k3s
  serviceName: kafka-k3s
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: kafka-k3s
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - kafka-k3s
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: kubernetes-kafka-k3s
          imagePullPolicy: Always
          image: "leonardorocha1990/pi-kafka:2.0.0-SNAPSHOT"
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx256M -Xms128M"
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
          ports:
            - containerPort: 9092
              name: client
          volumeMounts:
            - name: datadir
              mountPath: /kafka
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi